Feature/andwl 106 manage mnemonic
cosmostation/cosmostation-android pull request #193
Opened 2022-06-30 06:50 UTC by Kwonhyukjoon

Android - init mnemonic manage & DB upgrade

2022-07-01 05:10 UTC, soaryong-c requested changes

2022-07-01 05:10 UTC, soaryong-c commented on app/src/main/java/wannabit/io/cosmostaion/activities/PasswordCheckActivity.java
> +                    onDeleteAccount(getBaseDao().onSelectAccount("" + mIdToDelete));
String.valueOf(mIdToDelete)

2022-07-01 05:10 UTC, soaryong-c commented on app/src/main/java/wannabit/io/cosmostaion/activities/setting/WalletDeriveActivity.java
> +                    new Thread(() -> {
remove thread

2022-07-01 05:10 UTC, soaryong-c commented on app/src/main/java/wannabit/io/cosmostaion/activities/setting/WalletDeriveActivity.java
> +                    new Thread(() -> {
remove thread

2022-07-01 05:11 UTC, soaryong-c requested changes

2022-07-01 05:11 UTC, soaryong-c commented on app/src/main/java/wannabit/io/cosmostaion/activities/IntroActivity.java
> +    @SuppressLint("NewApi")
remove newapi, update minsdk 24

2022-07-03 14:14 UTC, wannabit-yongjoo approved these changes

2022-07-03 14:14 UTC, merged