[ANDWL-324] kado money add
cosmostation/cosmostation-android pull request #390
Opened 2022-10-27 06:28 UTC by kimheeje12

2022-10-27 07:55 UTC, soaryong-c requested changes

2022-10-27 07:55 UTC, soaryong-c commented on app/src/main/java/wannabit/io/cosmostaion/base/BaseActivity.java
> +        String query = "?apiKey=" + getString(R.string.moon_pay_public_key);
moon_pay_public_key

2022-10-27 07:55 UTC, soaryong-c commented on app/src/main/java/wannabit/io/cosmostaion/base/BaseConstant.java
> +    public final static boolean SUPPORT_PAY             = true;
not need.

2022-10-27 07:55 UTC, soaryong-c commented on app/src/main/java/wannabit/io/cosmostaion/widget/mainWallet/WalletPriceHolder.java
> +                if (mainActivity.mBaseChain.equals(COSMOS_MAIN) || mainActivity.mBaseChain.equals(BNB_MAIN) || mainActivity.mBaseChain.equals(KAVA_MAIN)) {
need refactoring

2022-10-28 06:38 UTC, Kwonhyukjoon commented on app/src/main/java/wannabit/io/cosmostaion/base/BaseActivity.java
> +        Toast.makeText(getBaseContext(), R.string.error_network_error, Toast.LENGTH_SHORT).show();
need this?

2022-10-28 06:54 UTC, kimheeje12 commented on app/src/main/java/wannabit/io/cosmostaion/base/BaseActivity.java
> +        Toast.makeText(getBaseContext(), R.string.error_network_error, Toast.LENGTH_SHORT).show();
Thank you

2022-11-01 15:20 UTC, soaryong-c approved these changes
👍

2022-11-01 15:20 UTC, soaryong-c commented
resolve conflicts please

2022-11-08 05:12 UTC, soaryong-c approved these changes
👍

2022-11-10 05:04 UTC, soaryong-c approved these changes
👍

2022-11-10 05:04 UTC, merged